modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersivePaintings/issues"
license = "GNU"

[[mods]]
modId = "immersive_paintings"
version = "${version}"
displayName = "Immersive Paintings"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ImmersivePaintings"
authors = "Luke100000"
description = '''
    Use your own paintings!
    '''
logoFile = "logoFile.png"

[[dependencies.immersive_paintings]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_paintings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
